In [2]:
import numpy as np

In [5]:
my_list = [1,2,3]
my_array = np.array([1,2,3])
print(type(my_list))

<class 'list'>


In [18]:
# Create a numpy array from a list

print(np.array(my_list))

[1 2 3]


In [19]:
# From a list of list

my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(my_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [20]:
# Creating arrays using built-in function
# Return evenly spaced values within a given interval

# Start, stop, step
print(np.arange(0,10))
print(np.arange(0,11,2))

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10]


In [21]:
# Generate arrays of zeros or ones

print(np.zeros(3))
print(np.zeros((5,5)))
print(np.ones(3))
print(np.ones((3,3)))

[0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
# Return evenly spaced nos over a specified interval
# Start, stop, no of elements (and not step)
# Unlike numpy.arrange(), the stop value is included in the result
# the spacing between values is automatically determined based on the specified no of values (num)

print(np.linspace(0,10,3))
print(np.linspace(0,5,20))
print(np.linspace(0,5,21))

[ 0.  5. 10.]
[0.         0.26315789 0.52631579 0.78947368 1.05263158 1.31578947
 1.57894737 1.84210526 2.10526316 2.36842105 2.63157895 2.89473684
 3.15789474 3.42105263 3.68421053 3.94736842 4.21052632 4.47368421
 4.73684211 5.        ]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25
 3.5  3.75 4.   4.25 4.5  4.75 5.  ]


In [16]:
# Random number arrays

print(np.random.rand(2))
print(np.random.rand(5,5))

[0.24485308 0.942419  ]
[[0.09028158 0.30048396 0.12770987 0.95514547 0.96517584]
 [0.12549828 0.32769885 0.6678081  0.55361159 0.67029742]
 [0.19456424 0.01274108 0.09532968 0.50226517 0.40431066]
 [0.0917542  0.37893946 0.74196113 0.68044814 0.95593134]
 [0.34574722 0.06592937 0.4914158  0.47883035 0.37170644]]


In [22]:
# From normal dstribution

print(np.random.randn(2))
print(np.random.randn(5,5))

# The graph of a normal distribution is a bell shaped curve

[-0.53340235 -0.87201138]
[[-0.86430769 -0.36296697  0.16779086 -0.24463917 -0.26157106]
 [-0.44255792 -0.67822462 -0.22259425  0.19329743  1.04450441]
 [-0.12442836 -0.4530511  -1.19017545  1.67969206  0.27321495]
 [-1.57786734 -0.02954774  1.57278617  0.81546234 -0.7369442 ]
 [-0.2260585  -1.54893417 -0.45641735 -0.11449053  0.5450463 ]]


In [ ]:
# From normal dstribution

print(np.random.randint(1,100))
print(np.random.randint(1, 100, 10))

In [29]:
# Seeding for reproducable result- random but predictble unlike random functon whose results are unpredictable
# We will get the same set of random numbers using seed.

np.random.seed(42)
print(np.random.rand(4))

np.random.seed(42)
print(np.random.rand(4))

[0.37454012 0.95071431 0.73199394 0.59865848]
[0.37454012 0.95071431 0.73199394 0.59865848]


In [64]:
# Storing

arr = np.arange(25)
ranarr = np.random.randint(0,50,10)
# 10 random nos between 0 to 50
print(arr)
print(ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[43  2 36  6 20  8 38 17  3 24]


In [65]:
# Reshape: Returns an array containing the same data with a new shape

print(arr.reshape(5,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [66]:
# Max, min and index positions

print(ranarr.max())
print(ranarr.argmax()) # Index position of max value in array
print(ranarr.min())

43
0
2


In [67]:
# Creating sample array

arr = np.arange(0,11)
print(arr)

# Bracket indexing and selection - similar to Python lists
# Get a value at an index

print(arr[8])

[ 0  1  2  3  4  5  6  7  8  9 10]
8


In [46]:
# Get values in a range

print(arr[1:5])
print(arr)

[1 2 3 4]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [47]:
# Broadcasting
# Setting a value with index range

arr[0:5] = 100
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]


In [48]:
# Reset array

arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [51]:
# Important notes on Slices

slice_of_arr = arr[0:6]
print(slice_of_arr)

[0 1 2 3 4 5]


In [54]:
# Changing slice

slice_of_arr[:] = 99
print(slice_of_arr)
print(arr)
# Changes made are also there in our original array
# Data is not copied, it is the view of the original array
# This avoid memory problems
# Similar to pointers

[99 99 99 99 99 99]
[99 99 99 99 99 99  6  7  8  9 10]


In [55]:
# To get a copy, we need to be explicit

arr_copy = arr.copy()
print(arr_copy)

[99 99 99 99 99 99  6  7  8  9 10]


In [60]:
# 2D Arrays

arr_2d = np.array(([5,10,15],[20,25,30],[30,35,40]))
print(arr_2d)

[[ 5 10 15]
 [20 25 30]
 [30 35 40]]


In [62]:
# Indexing row

print(arr_2d[1])

[20 25 30]


In [58]:
# Getting individual elemnt value
# Syntax is arr_2d[row][col] or arr_2d[row,col]

print(arr_2d[1,0])
print(arr_2d[1][0])

20
20


In [63]:
# 2D Array slicing
# shape (2,2) from top right corner

print(arr_2d[:2,1:])

[[10 15]
 [25 30]]


In [68]:
# Conditional selection
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [69]:
# Check each element of the rray aggainst the condition arr>4
# Whih returns a boolean array where each element is true if the corresponding eleent in the array is greates than 4 else false.

print(arr>4)
# Outhput: [False False False False  True  True  True  True  True  True]

bool_arr = arr>4
print(bool_arr)

[False False False False  True  True  True  True  True  True]
[False False False False  True  True  True  True  True  True]


In [70]:
# Select only those elements form the arr array where the corresponding element in bool_arr is true.
# It effectively filters out the elements of the arr where the condition arr>4 is true

print(arr[bool_arr])

[ 5  6  7  8  9 10]
