In [ ]:
import numpy as np

In [ ]:
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Basic Arithematic
print(arr + arr)
print(arr - arr)
print(arr * arr)

[ 0  2  4  6  8 10 12 14 16 18]
[0 0 0 0 0 0 0 0 0 0]
[ 0  1  4  9 16 25 36 49 64 81]


In [ ]:
# This will raise a waring on division with 0 but not an error. It just fills the spot with nan

print(arr / arr)

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]


C:\Users\Administrator.DAI-PC2\AppData\Local\Temp\ipykernel_19792\4078221113.py:3: RuntimeWarning: invalid value encountered in divide
  print(arr / arr)


In [ ]:
# A warning but not an error related to infinity

print(1 / arr)

[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]


C:\Users\Administrator.DAI-PC2\AppData\Local\Temp\ipykernel_19792\1196103188.py:3: RuntimeWarning: divide by zero encountered in divide
  print(1 / arr)


In [ ]:
print(arr**3)

[  0   1   8  27  64 125 216 343 512 729]


In [ ]:
# Universal Functions

# Taking Square Roots
print(np.sqrt(arr))

# Exponential (e^)
print(np.exp(arr))

# Sine
print(np.sin(arr))

# Taking SNatural Log
print(np.log(arr))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


C:\Users\Administrator.DAI-PC2\AppData\Local\Temp\ipykernel_19792\3685697315.py:13: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr))


In [ ]:
# Summary Statistics
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.var())
print(arr.std())

45
4.5
9
0
8.25
2.8722813232690143


In [ ]:
# 2D Arrays

# This is a 2D array with 3 rows and 4 columns
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# Sum all the columns for each row
print(arr_2d.sum(axis = 0))

# Sum all the rows for each column
print(arr_2d.sum(axis = 1))

[15 18 21 24]
[10 26 42]


In [ ]:
# Row and column count

print(arr_2d.shape)

(3, 4)
