**NumPy Questions**
- Write a NumPy program to get the numpy version and show numpy build configuration.
- Write a NumPy program to get help on the add function.
- Write a NumPy program to test whether none of the elements of a given array is zero.
- Write a NumPy program to test whether any of the elements of a given array is non-zero.
- Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).
- Write a NumPy program to test element-wise for positive or negative infinity.
- Write a NumPy program to test element-wise for NaN of a given array.
- Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.
- Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.
- Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.
- Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.
- Write a NumPy program to create an array of the integers from 30 to70.
- Write a NumPy program to create an array of all the even integers from 30 to 70.
- Write a NumPy program to create a 3x3 identity matrix.
- Write a NumPy program to generate a random number between 0 and 1.
- Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.
- Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.
- Write a NumPy program to create a 3X4 array using and iterate over it.
- Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.
- Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.
- Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.
- Write a NumPy program to multiply the values of two given vectors.
- Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.
- Write a NumPy program to find the number of rows and columns of a given matrix.
- Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0.
- Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.
- Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.
- Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.
- Write a NumPy program to create a 3x3x3 array filled with arbitrary values.
- Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.
- Write a NumPy program to compute the inner product of two given vectors.
- Write a NumPy program to add a vector to each row of a given matrix.
- Write a NumPy program to compute the x and y coordinates for points on a sine curve and plot the points using matplotlib.
- Write a NumPy program to convert numpy dtypes to native python types.
- Write a NumPy program to find the missing data in a given array.
- Write a NumPy program to sort a given array by row and column in ascending order.
- Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.
- Write a NumPy program to replace all numbers in a given array which is equal, less and greater to a given number.
- Write a NumPy program to create an array of equal shape and data type of a given array.
- Write a NumPy program to create a three-dimension array with shape (3,5,4) and set to a variable.
- Write a NumPy program to multiply two given arrays of same size element-by-element.

In [ ]:
import numpy as np

In [ ]:
# 1. Write a NumPy program to get the numpy version and show numpy build configuration.
print("NumPy Version:",np.__version__)
print("Configuration:",np.show_config())

In [ ]:
# 2. Write a NumPy program to get help on the add function.
print(np.info(np.add))

In [ ]:
# 3. Write a NumPy program to test whether none of the elements of a given array is zero.
arr = np.array([1,2,0,4,5,0])
non_zero = np.any(arr != 0)
print("Original array:",arr)
print("\nElements of a given array is zero:",non_zero)
print("Element check:",arr == 0)

Original array: [1 2 0 4 5 0]

Elements of a given array is zero: True
Element check: [False False  True False False  True]


In [ ]:
# 4. Write a NumPy program to test whether any of the elements of a given array is non-zero
arr = np.array([1,2,0,4,5,0])
zeros = np.any(arr != 0)
print("Original array:",arr)
print("\nElements of a given array is non-zero:",zeros)
print("Element check:",arr == 0)

Original array: [1 2 0 4 5 0]

Elements of a given array is non-zero: True
Element check: [False False  True False False  True]


In [ ]:
# 5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).
arr = np.array([1, 2, np.inf, 4, 5, np.nan])
finite_elements = np.isfinite(arr)

# Print the results
print("Original array:",arr)
print("\nElement-wise for finiteness:",finite_elements)

Original array: [ 1.  2. inf  4.  5. nan]

Test element-wise for finiteness: [ True  True False  True  True False]


In [ ]:
# 6. Write a NumPy program to test element-wise for positive or negative infinity
arr = np.array([np.inf, 2, np.NINF, 4, 5, np.nan])
non_infi = np.isinf(arr)

print("Original array:",arr)
print("\nElement-wise check:",non_infi)

Original array: [ inf   2. -inf   4.   5.  nan]

Element-wise check: [ True False  True False False False]


In [ ]:
# 7. Write a NumPy program to test element-wise for NaN of a given array.
arr = np.array([np.inf, 2, np.nan, np.NINF, np.nan, 4, 5, np.nan])
nan_element = np.isnan(arr)

print("Original array:",arr)
print("\nElement-wise check:",nan_element)

Original array: [ inf   2.  nan -inf  nan   4.   5.  nan]

Element-wise check: [False False  True False  True False False  True]


In [ ]:
# 8. Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.
arr = np.array([1, 2+3j, 4.5, 6, 7j, 8+9j]) #use j and not i
arr1 = np.array([1,2,3,4,5])
complex_element = np.iscomplex(arr)
real_no = np.isreal(arr)
for e in arr:
  scalar_no = np.isscalar(e)
  print("\nElement-wise check for Scalar Number:",scalar_no)

print(arr)
print("\nElement-wise check for Complex Number:",complex_element)
print("\nElement-wise check for Real Number:",real_no)


In [ ]:
# 9. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,2,1,2,7])

greater = np.greater(arr1,arr2)
print("Element-wise comparison - Greater:",greater)

greater_equal = np.greater_equal(arr1,arr2)
print("Element-wise comparison - Greater-Equal:",greater_equal)

less = np.less(arr1,arr2)
print("Element-wise comparison - Less:",less)

less_equal = np.less(arr1,arr2)
print("Element-wise comparison - Less-Equal:",less_equal)

Element-wise comparison - Greater: [False False  True  True False]
Element-wise comparison - Greater-Equal: [False  True  True  True False]
Element-wise comparison - Less: [ True False False False  True]
Element-wise comparison - Less-Equal: [ True False False False  True]


In [ ]:
# 10. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.
import sys

arr = np.array([1,7,13,105])
size = sys.getsizeof(arr)

print("Array: ",arr)
print("Size occupied: ",size)

Array:  [  1   7  13 105]
Size occupied:  144


In [ ]:
# 11. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

zeros = np.zeros(10)
ones = np.ones(10)
fives = np.full(10,5)

arr = np.concatenate((zeros,ones,fives))
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


In [ ]:
# 12. Write a NumPy program to create an array of the integers from 30 to 70.
arr = np.arange(30,71)
print(arr)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [ ]:
# 13. Write a NumPy program to create a 3x3 identity matrix.
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 14. Write a NumPy program to generate a random number between 0 and 1.
random_no = np.random.rand(1)
print(random_no)

[0.04804619]


In [ ]:
# 15. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.
random_no = np.random.rand(15)
print(random_no)

[0.39982946 0.8037864  0.08863792 0.75501229 0.9743014  0.37458031
 0.05381024 0.17527188 0.8244024  0.65153442 0.88200528 0.54675709
 0.09642198 0.21138932 0.45841007]


In [ ]:
# 16. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.
vector = np.arange(15,56)
print(vector[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [ ]:
# 17. Write a NumPy program to create a 3X4 array using and iterate over it.